# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'windows-2019'

  steps:
  - task: giuliovdev.hugo-extension.hugo-build-task.HugoTask@1
    displayName: 'Hugo generate '
    inputs:
      destination: '$(Build.ArtifactStagingDirectory)'

  - task: AzureFileCopy@2
    displayName: 'AzureBlob File Copy'
    inputs:
      SourcePath: '$(Build.ArtifactStagingDirectory)'
      azureSubscription: 'Microsoft Partner Network (9f9311cf-d0ca-4526-8677-69c74798c84e)'
      Destination: AzureBlob
      storage: buzzybeewebsite
      ContainerName: '$web'
    
  - task: fabienlavocat.FabienLavocat-PurgeAzureCDNEndpoint.PurgeAzureCDNEndpoint.PurgeAzureCDNEndpoint@2
    displayName: 'Purge Azure CDN Endpoint'
    inputs:
      ConnectedServiceNameSelector: ConnectedServiceNameARM
      ConnectedServiceNameARM: 'Microsoft Partner Network(1)(9f9311cf-d0ca-4526-8677-69c74798c84e)'
      ResourceGroupName: barrit
      EndpointName: buzzybee
      ProfileName: 'barrit-cdn'